const targetKeywordGroups = {
  marketing: [
    "marketing",
    "market",
    "consumer marketing",
    "product marketing",
    "digital marketing",
    "content marketing",
    "social",
    "campaign",
    "media",
    "传播",
    "市场",
    "营销",
  ],
  branding: [
    "brand",
    "branding",
    "brand manager",
    "brand communication",
    "brand strategy",
    "品牌",
    "品牌传播",
  ],
  npd: [
    "innovation",
    "new product",
    "npd",
    "product development",
    "product manager",
    "product innovation",
    "新品",
    "创新",
    "产品",
  ],
  o2o: [
    "o2o",
    "omni",
    "omnichannel",
    "e-commerce",
    "ecommerce",
    "e-com",
    "digital commerce",
    "tmall",
    "jd",
    "douyin",
    "retail media",
    "instant retail",
    "即时零售",
    "全渠道",
    "电商",
  ],
  category: [
    "category",
    "trade marketing",
    "shopper",
    "retail marketing",
    "merchandising",
    "assortment",
    "品类",
    "商品",
    "渠道",
  ],
  insights: [
    "consumer insight",
    "consumer insights",
    "market research",
    "insight",
    "analytics",
    "用户洞察",
    "消费者洞察",
  ],
};

const negativeTitleKeywords = [
  "store associate",
  "sales associate",
  "beauty advisor",
  "counter manager",
  "retail assistant",
  "warehouse",
  "internship",
  "intern ",
  "实习",
  "导购",
  "店员",
  "柜员",
  "仓库",
];

const profileKeywords = [
  "consumer insight",
  "trend",
  "innovation",
  "new product",
  "npd",
  "brand",
  "content",
  "xiaohongshu",
  "e-commerce",
  "tmall",
  "o2o",
  "omnichannel",
  "retail media",
  "category",
  "trade marketing",
  "gmv",
  "launch",
  "go-to-market",
  "cross-functional",
  "english",
  "产品创新",
  "新品",
  "品牌",
  "内容",
  "小红书",
  "电商",
  "即时零售",
  "品类",
  "上市",
  "消费者洞察",
];

const careerSources = [
  {
    id: "loreal",
    company: "欧莱雅 L'Oreal Groupe",
    industry: "美妆个护",
    priority: "A",
    brands: ["Lancome", "YSL Beauty", "Kiehl's", "Maybelline", "3CE", "Aesop"],
    careersUrl: "https://careers.loreal.com/",
    searchUrls: [
      "https://careers.loreal.com/en_US/jobs/SearchJobs?keyword=marketing&location=Shanghai",
      "https://careers.loreal.com/en_US/jobs/SearchJobs?keyword=brand&location=Shanghai",
      "https://careers.loreal.com/en_US/jobs/SearchJobs?keyword=e-commerce&location=Shanghai",
    ],
  },
  {
    id: "elcompanies",
    company: "雅诗兰黛集团 Estée Lauder Companies",
    industry: "美妆个护",
    priority: "A",
    brands: ["Estée Lauder", "Clinique", "MAC", "La Mer", "Jo Malone", "Bobbi Brown", "Tom Ford Beauty"],
    careersUrl: "https://careers.elcompanies.com/",
    searchUrls: [
      "https://careers.elcompanies.com/jobs?location=Shanghai%2C%20China",
      "https://careers.elcompanies.com/jobs?keywords=marketing&location=Shanghai",
    ],
  },
  {
    id: "shiseido",
    company: "资生堂 Shiseido",
    industry: "美妆个护",
    priority: "A",
    brands: ["Shiseido", "NARS", "Clé de Peau Beauté", "IPSA", "Anessa"],
    careersUrl: "https://careers.shiseido.com/job",
    searchUrls: ["https://careers.shiseido.com/search/?q=marketing&locationsearch=Shanghai"],
  },
  {
    id: "henkel",
    company: "汉高 Henkel Consumer Brands",
    industry: "美妆个护",
    priority: "A",
    brands: ["Schwarzkopf", "Syoss 丝蕴", "Vidal Sassoon 沙宣", "got2b", "Persil"],
    careersUrl: "https://www.henkel.com/careers",
    searchUrls: [
      "https://www.henkel.com/careers/jobs-and-application?country=China&location=Shanghai",
      "https://www.henkel.com/careers/jobs-and-application?search=marketing&country=China",
    ],
  },
  {
    id: "pg",
    company: "宝洁 P&G",
    industry: "美妆个护",
    priority: "A",
    brands: ["SK-II", "Olay", "Pantene", "Head & Shoulders", "Pampers", "Oral-B"],
    careersUrl: "https://careers.pg.com.cn/cn/en",
    searchUrls: ["https://careers.pg.com.cn/cn/en/search-results?keywords=marketing&location=Shanghai"],
  },
  {
    id: "unilever",
    company: "联合利华 Unilever",
    industry: "美妆个护 / 食品饮料",
    priority: "A",
    brands: ["Dove", "Lux", "Clear", "Vaseline", "Magnum", "Wall's"],
    careersUrl: "https://careers.unilever.com/search-jobs",
    searchUrls: [
      "https://careers.unilever.com/en/location/shanghai-jobs/34155/1814991-1796231-1796236/4",
      "https://careers.unilever.com/search-jobs/marketing/34155/1",
    ],
  },
  {
    id: "beiersdorf",
    company: "拜尔斯道夫 Beiersdorf",
    industry: "美妆个护",
    priority: "A",
    brands: ["NIVEA", "Eucerin", "La Prairie"],
    careersUrl: "https://www.en.beiersdorf.cn/career/application/open-positions",
    searchUrls: ["https://www.en.beiersdorf.cn/career/application/open-positions"],
  },
  {
    id: "kenvue",
    company: "科赴 Kenvue",
    industry: "消费健康",
    priority: "A",
    brands: ["Neutrogena", "Aveeno", "Listerine", "Johnson's", "Band-Aid", "Tylenol"],
    careersUrl: "https://www.kenvue.com/careers",
    searchUrls: ["https://www.kenvue.com/careers/search-jobs?keyword=marketing&location=Shanghai"],
  },
  {
    id: "haleon",
    company: "Haleon",
    industry: "消费健康",
    priority: "A",
    brands: ["Sensodyne", "Centrum", "Caltrate", "Panadol", "Voltaren"],
    careersUrl: "https://www.haleon.com/careers",
    searchUrls: ["https://www.haleon.com/careers/job-search?keyword=marketing&location=Shanghai"],
  },
  {
    id: "reckitt",
    company: "利洁时 Reckitt",
    industry: "美妆个护 / 家清日化",
    priority: "A",
    brands: ["Dettol", "Durex", "Finish", "Strepsils", "Move Free"],
    careersUrl: "https://careers.reckitt.com/",
    searchUrls: ["https://careers.reckitt.com/search-jobs/Shanghai/3757/1814991-1796231-1796236/4"],
  },
  {
    id: "colgate",
    company: "高露洁 Colgate-Palmolive",
    industry: "美妆个护 / 宠物",
    priority: "B",
    brands: ["Colgate", "Palmolive", "Hill's Pet Nutrition"],
    careersUrl: "https://jobs.colgate.com/",
    searchUrls: ["https://jobs.colgate.com/search/?q=marketing&locationsearch=Shanghai"],
  },
  {
    id: "kimberly-clark",
    company: "金佰利 Kimberly-Clark",
    industry: "美妆个护 / 母婴",
    priority: "B",
    brands: ["Huggies", "Kotex", "Kleenex"],
    careersUrl: "https://careers.kimberly-clark.com/en/job-search",
    searchUrls: ["https://careers.kimberly-clark.com/en/job-search?search=marketing&location=Shanghai"],
  },
  {
    id: "scjohnson",
    company: "庄臣 SC Johnson",
    industry: "家清日化",
    priority: "B",
    brands: ["Mr Muscle", "Ziploc", "Glade", "Raid"],
    careersUrl: "https://jobs.scjohnson.com/en/china",
    searchUrls: ["https://jobs.scjohnson.com/en/search-jobs/Shanghai/25146/1814991-1796231-1796236/4"],
  },
  {
    id: "kao",
    company: "花王 Kao",
    industry: "美妆个护 / 家清日化",
    priority: "B",
    brands: ["Kao", "Bioré", "Curél", "Laurier", "Merit"],
    careersUrl: "https://www.kao.com/global/en/careers/",
    searchUrls: ["https://www.kao.com/global/en/careers/"],
  },
  {
    id: "coty",
    company: "科蒂 Coty",
    industry: "美妆个护",
    priority: "A",
    brands: ["Gucci Beauty", "Burberry Beauty", "Chloé", "Calvin Klein Fragrance", "Rimmel"],
    careersUrl: "https://careers.coty.com/",
    searchUrls: ["https://careers.coty.com/search/?q=marketing&locationsearch=Shanghai"],
  },
  {
    id: "amorepacific",
    company: "爱茉莉太平洋 Amorepacific",
    industry: "美妆个护",
    priority: "A",
    brands: ["Sulwhasoo", "Laneige", "Innisfree", "Ryo"],
    careersUrl: "https://www.apgroup.com/int/en/careers/careers.html",
    searchUrls: ["https://www.apgroup.com/int/en/careers/careers.html"],
  },
  {
    id: "loccitane",
    company: "欧舒丹集团 L'OCCITANE Group",
    industry: "美妆个护 / 零售",
    priority: "B",
    brands: ["L'OCCITANE", "Elemis", "Melvita", "Sol de Janeiro"],
    careersUrl: "https://group.loccitane.com/careers",
    searchUrls: ["https://group.loccitane.com/careers?location=Shanghai"],
  },
  {
    id: "clarins",
    company: "娇韵诗 Clarins",
    industry: "美妆个护",
    priority: "B",
    brands: ["Clarins", "myBlend"],
    careersUrl: "https://www.groupeclarins.com/en/careers/",
    searchUrls: ["https://www.groupeclarins.com/en/careers/"],
  },
  {
    id: "puig",
    company: "Puig",
    industry: "美妆个护",
    priority: "B",
    brands: ["Rabanne", "Carolina Herrera", "Jean Paul Gaultier", "Byredo", "Charlotte Tilbury"],
    careersUrl: "https://www.puig.com/en/careers/",
    searchUrls: ["https://www.puig.com/en/careers/?location=China"],
  },
  {
    id: "mary-kay",
    company: "Mary Kay",
    industry: "美妆个护",
    priority: "C",
    brands: ["Mary Kay"],
    careersUrl: "https://www.marykay.com.cn/",
    searchUrls: ["https://www.marykay.com.cn/"],
  },
  {
    id: "nestle",
    company: "雀巢 Nestlé",
    industry: "食品饮料 / 宠物 / 营养",
    priority: "A",
    brands: ["Nescafé", "Starbucks RTD", "KitKat", "Purina", "Wyeth Nutrition"],
    careersUrl: "https://www.nestle.com/jobs/search-jobs",
    searchUrls: ["https://www.nestle.com/jobs/search-jobs?keyword=marketing&location=Shanghai"],
  },
  {
    id: "mars",
    company: "玛氏 Mars",
    industry: "食品饮料 / 宠物",
    priority: "A",
    brands: ["M&M's", "Snickers", "Dove 德芙", "Wrigley", "Pedigree", "Royal Canin"],
    careersUrl: "https://www.mars.com/careers/find-jobs",
    searchUrls: ["https://www.mars.com/careers/find-jobs?keywords=marketing&location=Shanghai"],
  },
  {
    id: "mondelez",
    company: "亿滋 Mondelez",
    industry: "食品饮料",
    priority: "A",
    brands: ["Oreo", "belVita", "Toblerone", "Cadbury", "Milka", "Ritz"],
    careersUrl: "https://www.mondelezinternational.com/Careers/",
    searchUrls: ["https://www.mondelezinternational.com/Careers/?search=marketing&location=Shanghai"],
  },
  {
    id: "danone",
    company: "达能 Danone",
    industry: "食品饮料 / 营养",
    priority: "A",
    brands: ["Aptamil", "Nutricia", "Evian", "Mizone", "Alpro"],
    careersUrl: "https://careers.danone.com/",
    searchUrls: ["https://careers.danone.com/search/?q=marketing&locationsearch=Shanghai"],
  },
  {
    id: "coca-cola",
    company: "可口可乐 The Coca-Cola Company",
    industry: "食品饮料",
    priority: "A",
    brands: ["Coca-Cola", "Sprite", "Fanta", "Costa Coffee RTD"],
    careersUrl: "https://www.coca-colacompany.com/careers",
    searchUrls: ["https://www.coca-colacompany.com/careers?keyword=marketing&location=Shanghai"],
  },
  {
    id: "pepsico",
    company: "百事 PepsiCo",
    industry: "食品饮料",
    priority: "A",
    brands: ["Lay's", "Quaker", "Pepsi", "Gatorade", "Doritos"],
    careersUrl: "https://www.pepsicojobs.com/china",
    searchUrls: [
      "https://www.pepsicojobs.com/main/jobs?location=Shanghai%2C%20China",
      "https://www.pepsicojobs.com/china/jobs?keywords=marketing&location=Shanghai",
    ],
  },
  {
    id: "ferrero",
    company: "费列罗 Ferrero",
    industry: "食品饮料",
    priority: "A",
    brands: ["Ferrero Rocher", "Kinder", "Nutella", "Tic Tac"],
    careersUrl: "https://www.ferrerocareers.com/zh/en",
    searchUrls: ["https://www.ferrerocareers.com/zh/en/search-results?keywords=marketing&location=Shanghai"],
  },
  {
    id: "jde-peets",
    company: "JDE Peet's",
    industry: "食品饮料 / 咖啡",
    priority: "A",
    brands: ["Peet's Coffee", "Jacobs", "Moccona", "L'OR"],
    careersUrl: "https://careers-cn.jdepeets.com/",
    searchUrls: ["https://careers-cn.jdepeets.com/?search=marketing&location=Shanghai"],
  },
  {
    id: "starbucks",
    company: "星巴克中国 Starbucks China",
    industry: "食品饮料 / 零售",
    priority: "B",
    brands: ["Starbucks"],
    careersUrl: "https://www.starbucks.com.cn/about/careers/",
    searchUrls: ["https://www.starbucks.com.cn/about/careers/"],
  },
  {
    id: "ab-inbev",
    company: "百威英博 AB InBev",
    industry: "食品饮料 / 酒水",
    priority: "B",
    brands: ["Budweiser", "Corona", "Hoegaarden", "Harbin"],
    careersUrl: "https://www.ab-inbev.com/working-with-us",
    searchUrls: ["https://www.ab-inbev.com/working-with-us?search=marketing&location=Shanghai"],
  },
  {
    id: "diageo",
    company: "帝亚吉欧 Diageo",
    industry: "食品饮料 / 酒水",
    priority: "A",
    brands: ["Johnnie Walker", "Singleton", "Tanqueray", "Baileys", "Guinness"],
    careersUrl: "https://www.diageo.com/en/careers/search-and-apply",
    searchUrls: ["https://www.diageo.com/en/careers/search-and-apply?keyword=marketing&location=Shanghai"],
  },
  {
    id: "pernod-ricard",
    company: "保乐力加 Pernod Ricard",
    industry: "食品饮料 / 酒水",
    priority: "A",
    brands: ["Absolut", "Chivas", "Martell", "Jameson", "Ballantine's"],
    careersUrl: "https://www.pernod-ricard.com/en/career-homepage",
    searchUrls: ["https://www.pernod-ricard.com/en/career-homepage"],
  },
  {
    id: "heineken",
    company: "喜力 Heineken",
    industry: "食品饮料 / 酒水",
    priority: "C",
    brands: ["Heineken", "Tiger"],
    careersUrl: "https://careers.theheinekencompany.com/",
    searchUrls: ["https://careers.theheinekencompany.com/search/?q=marketing&locationsearch=Shanghai"],
  },
  {
    id: "carlsberg",
    company: "嘉士伯 Carlsberg",
    industry: "食品饮料 / 酒水",
    priority: "C",
    brands: ["Carlsberg", "Tuborg", "1664"],
    careersUrl: "https://careers.carlsberg.com/",
    searchUrls: ["https://careers.carlsberg.com/search/?q=marketing&locationsearch=Shanghai"],
  },
  {
    id: "bacardi",
    company: "Bacardi",
    industry: "食品饮料 / 酒水",
    priority: "B",
    brands: ["Bacardi", "Grey Goose", "Bombay Sapphire", "Dewar's"],
    careersUrl: "https://www.bacardilimited.com/careers/",
    searchUrls: ["https://www.bacardilimited.com/careers/?search=marketing&location=Shanghai"],
  },
  {
    id: "suntory-global-spirits",
    company: "Suntory Global Spirits",
    industry: "食品饮料 / 酒水",
    priority: "B",
    brands: ["Jim Beam", "Maker's Mark", "Hibiki", "Yamazaki"],
    careersUrl: "https://www.suntoryglobalspirits.com/careers/",
    searchUrls: ["https://www.suntoryglobalspirits.com/careers/?search=marketing&location=Shanghai"],
  },
  {
    id: "remy-cointreau",
    company: "Rémy Cointreau",
    industry: "食品饮料 / 酒水",
    priority: "B",
    brands: ["Rémy Martin", "Cointreau", "Mount Gay"],
    careersUrl: "https://www.remy-cointreau.com/en/careers/",
    searchUrls: ["https://www.remy-cointreau.com/en/careers/"],
  },
  {
    id: "general-mills",
    company: "通用磨坊 General Mills",
    industry: "食品饮料",
    priority: "A",
    brands: ["Häagen-Dazs", "Wanchai Ferry", "Blue Buffalo"],
    careersUrl: "https://careers.generalmills.com/careers/",
    searchUrls: ["https://careers.generalmills.com/careers/?keywords=marketing&location=Shanghai"],
  },
  {
    id: "kellanova",
    company: "Kellanova",
    industry: "食品饮料",
    priority: "B",
    brands: ["Pringles", "Cheez-It", "Pop-Tarts"],
    careersUrl: "https://www.kellanovacareers.com/",
    searchUrls: ["https://www.kellanovacareers.com/search/?q=marketing&locationsearch=Shanghai"],
  },
  {
    id: "kraft-heinz",
    company: "卡夫亨氏 Kraft Heinz",
    industry: "食品饮料",
    priority: "B",
    brands: ["Heinz", "Master", "Guanghe"],
    careersUrl: "https://careers.kraftheinz.com/locations/china/",
    searchUrls: ["https://careers.kraftheinz.com/search/?q=marketing&locationsearch=Shanghai"],
  },
  {
    id: "mccormick",
    company: "味好美 McCormick",
    industry: "食品饮料",
    priority: "B",
    brands: ["McCormick", "French's", "Frank's RedHot"],
    careersUrl: "https://careers.mccormick.com/",
    searchUrls: ["https://careers.mccormick.com/search/?q=marketing&locationsearch=Shanghai"],
  },
  {
    id: "fonterra",
    company: "恒天然 Fonterra",
    industry: "食品饮料 / 营养",
    priority: "B",
    brands: ["Anchor", "Anlene", "Anmum", "NZMP"],
    careersUrl: "https://careers.fonterra.com/careers/Greater-China-Careers",
    searchUrls: ["https://careers.fonterra.com/careers/Greater-China-Careers?search=marketing&location=Shanghai"],
  },
  {
    id: "frieslandcampina",
    company: "菲仕兰 FrieslandCampina",
    industry: "食品饮料 / 营养",
    priority: "B",
    brands: ["Friso", "Dutch Lady"],
    careersUrl: "https://careers.frieslandcampina.com/",
    searchUrls: ["https://careers.frieslandcampina.com/search/?q=marketing&locationsearch=Shanghai"],
  },
  {
    id: "arla",
    company: "Arla Foods",
    industry: "食品饮料",
    priority: "C",
    brands: ["Arla", "Lurpak", "Castello"],
    careersUrl: "https://www.arla.com/company/job-and-career/",
    searchUrls: ["https://www.arla.com/company/job-and-career/"],
  },
  {
    id: "barry-callebaut",
    company: "Barry Callebaut",
    industry: "食品饮料",
    priority: "B",
    brands: ["Chocolate Academy"],
    careersUrl: "https://www.barry-callebaut.com/en-GB/careers",
    searchUrls: ["https://www.barry-callebaut.com/en-GB/careers?location=Shanghai"],
  },
  {
    id: "barilla",
    company: "Barilla",
    industry: "食品饮料",
    priority: "C",
    brands: ["Barilla", "Wasa"],
    careersUrl: "https://www.barillagroup.com/en/careers/",
    searchUrls: ["https://www.barillagroup.com/en/careers/"],
  },
  {
    id: "lindt",
    company: "Lindt & Sprüngli",
    industry: "食品饮料 / 零售",
    priority: "C",
    brands: ["Lindt", "Ghirardelli"],
    careersUrl: "https://www.lindt-spruengli.com/careers",
    searchUrls: ["https://www.lindt-spruengli.com/careers"],
  },
  {
    id: "ikea",
    company: "宜家 IKEA",
    industry: "零售 / 家居",
    priority: "A",
    brands: ["IKEA"],
    careersUrl: "https://jobs.ikea.com/en/location/shanghai-jobs/22908/1814991-1796231-1796236/4/1",
    searchUrls: ["https://jobs.ikea.com/en/location/shanghai-jobs/22908/1814991-1796231-1796236/4/1"],
  },
  {
    id: "costco",
    company: "Costco 开市客",
    industry: "零售",
    priority: "B",
    brands: ["Costco"],
    careersUrl: "https://www.costco.com.cn/",
    searchUrls: ["https://www.costco.com.cn/"],
  },
  {
    id: "decathlon",
    company: "迪卡侬 Decathlon",
    industry: "零售 / 运动生活方式",
    priority: "A",
    brands: ["Decathlon"],
    careersUrl: "https://recruitment.decathlon.com.cn/",
    searchUrls: ["https://recruitment.decathlon.com.cn/"],
  },
  {
    id: "uniqlo",
    company: "迅销 Fast Retailing / UNIQLO",
    industry: "零售 / 时尚",
    priority: "A",
    brands: ["UNIQLO", "GU", "Theory"],
    careersUrl: "https://www.uniqlo.com/cn/employment/recruit.html",
    searchUrls: ["https://www.uniqlo.com/cn/employment/recruit.html"],
  },
  {
    id: "muji",
    company: "无印良品 MUJI",
    industry: "零售 / 生活方式",
    priority: "B",
    brands: ["MUJI"],
    careersUrl: "https://careers.muji.com/jp/",
    searchUrls: ["https://careers.muji.com/jp/"],
  },
  {
    id: "nike",
    company: "耐克 Nike",
    industry: "零售 / 运动生活方式",
    priority: "A",
    brands: ["Nike", "Jordan", "Converse"],
    careersUrl: "https://jobs.nike.com/",
    searchUrls: ["https://jobs.nike.com/search?location=Shanghai%2C%20China&keyword=marketing"],
  },
  {
    id: "adidas",
    company: "阿迪达斯 adidas",
    industry: "零售 / 运动生活方式",
    priority: "A",
    brands: ["adidas", "Originals"],
    careersUrl: "https://careers.adidas-group.com/",
    searchUrls: ["https://careers.adidas-group.com/search/?q=marketing&locationsearch=Shanghai"],
  },
  {
    id: "puma",
    company: "PUMA",
    industry: "零售 / 运动生活方式",
    priority: "B",
    brands: ["PUMA"],
    careersUrl: "https://about.puma.com/en/careers",
    searchUrls: ["https://about.puma.com/en/careers?location=Shanghai"],
  },
  {
    id: "skechers",
    company: "Skechers",
    industry: "零售 / 运动生活方式",
    priority: "B",
    brands: ["Skechers"],
    careersUrl: "https://www.skechers.com/careers/",
    searchUrls: ["https://www.skechers.com/careers/"],
  },
  {
    id: "new-balance",
    company: "New Balance",
    industry: "零售 / 运动生活方式",
    priority: "B",
    brands: ["New Balance"],
    careersUrl: "https://jobs.newbalance.com/",
    searchUrls: ["https://jobs.newbalance.com/search/?q=marketing&locationsearch=Shanghai"],
  },
  {
    id: "asics",
    company: "ASICS",
    industry: "零售 / 运动生活方式",
    priority: "B",
    brands: ["ASICS", "Onitsuka Tiger"],
    careersUrl: "https://corp.asics.com/en/careers",
    searchUrls: ["https://corp.asics.com/en/careers"],
  },
  {
    id: "on",
    company: "On",
    industry: "零售 / 运动生活方式",
    priority: "A",
    brands: ["On Running"],
    careersUrl: "https://www.on.com/en-us/careers",
    searchUrls: ["https://www.on.com/en-us/careers?location=Shanghai"],
  },
  {
    id: "lululemon",
    company: "lululemon",
    industry: "零售 / 运动生活方式",
    priority: "A",
    brands: ["lululemon"],
    careersUrl: "https://careers.lululemon.com/",
    searchUrls: ["https://careers.lululemon.com/en_US/careers/SearchJobs?keyword=marketing&location=Shanghai"],
  },
  {
    id: "hm",
    company: "H&M Group",
    industry: "零售 / 时尚",
    priority: "B",
    brands: ["H&M", "COS", "& Other Stories", "Monki", "ARKET"],
    careersUrl: "https://career.hm.com/",
    searchUrls: ["https://career.hm.com/search-jobs?location=Shanghai"],
  },
  {
    id: "inditex",
    company: "Inditex",
    industry: "零售 / 时尚",
    priority: "B",
    brands: ["Zara", "Massimo Dutti", "Pull&Bear", "Bershka", "Oysho"],
    careersUrl: "https://www.inditexcareers.com/",
    searchUrls: ["https://www.inditexcareers.com/portalweb/en/search?keyword=Shanghai"],
  },
  {
    id: "gap",
    company: "Gap Inc.",
    industry: "零售 / 时尚",
    priority: "C",
    brands: ["Gap", "Old Navy", "Athleta", "Banana Republic"],
    careersUrl: "https://www.gapinc.com/en-us/careers",
    searchUrls: ["https://www.gapinc.com/en-us/careers?location=Shanghai"],
  },
  {
    id: "levi",
    company: "Levi Strauss & Co.",
    industry: "零售 / 时尚",
    priority: "B",
    brands: ["Levi's", "Dockers"],
    careersUrl: "https://www.levistrauss.com/careers/",
    searchUrls: ["https://www.levistrauss.com/careers/?location=Shanghai"],
  },
  {
    id: "vf",
    company: "VF Corporation",
    industry: "零售 / 户外潮流",
    priority: "A",
    brands: ["The North Face", "Vans", "Timberland", "Dickies"],
    careersUrl: "https://www.vfc.com/careers",
    searchUrls: ["https://www.vfc.com/careers?location=Shanghai"],
  },
  {
    id: "under-armour",
    company: "Under Armour",
    industry: "零售 / 运动生活方式",
    priority: "B",
    brands: ["Under Armour"],
    careersUrl: "https://careers.underarmour.com/",
    searchUrls: ["https://careers.underarmour.com/search/?q=marketing&locationsearch=Shanghai"],
  },
  {
    id: "columbia",
    company: "Columbia Sportswear",
    industry: "零售 / 户外潮流",
    priority: "B",
    brands: ["Columbia", "SOREL", "Mountain Hardwear"],
    careersUrl: "https://www.columbiasportswearcompany.com/careers/",
    searchUrls: ["https://www.columbiasportswearcompany.com/careers/?location=Shanghai"],
  },
  {
    id: "dyson",
    company: "Dyson",
    industry: "零售 / 个护科技",
    priority: "A",
    brands: ["Dyson"],
    careersUrl: "https://careers.dyson.com/",
    searchUrls: ["https://careers.dyson.com/search-jobs?keyword=marketing&location=Shanghai"],
  },
  {
    id: "philips",
    company: "Philips Personal Health",
    industry: "个护科技 / 消费健康",
    priority: "A",
    brands: ["Philips Sonicare", "Avent", "Grooming", "Personal Health"],
    careersUrl: "https://www.careers.philips.com/",
    searchUrls: ["https://www.careers.philips.com/global/en/search-results?keywords=marketing&location=Shanghai"],
  },
  {
    id: "lego",
    company: "LEGO Group",
    industry: "零售 / 玩具",
    priority: "A",
    brands: ["LEGO"],
    careersUrl: "https://www.lego.com/en-us/careers",
    searchUrls: ["https://www.lego.com/en-us/careers/search?location=Shanghai"],
  },
  {
    id: "mattel",
    company: "Mattel",
    industry: "零售 / 玩具",
    priority: "B",
    brands: ["Barbie", "Hot Wheels", "Fisher-Price"],
    careersUrl: "https://jobs.mattel.com/",
    searchUrls: ["https://jobs.mattel.com/search/?q=marketing&locationsearch=Shanghai"],
  },
  {
    id: "hasbro",
    company: "Hasbro",
    industry: "零售 / 玩具",
    priority: "B",
    brands: ["Transformers", "Monopoly", "Nerf", "Peppa Pig"],
    careersUrl: "https://jobs.hasbro.com/",
    searchUrls: ["https://jobs.hasbro.com/search/?q=marketing&locationsearch=Shanghai"],
  },
  {
    id: "lvmh",
    company: "LVMH",
    industry: "奢侈品 / 美妆 / 零售",
    priority: "A",
    brands: ["Louis Vuitton", "Dior", "Fendi", "Celine", "Sephora", "LVMH Beauty", "Moët Hennessy"],
    careersUrl: "https://www.lvmh.cn/job-offers",
    searchUrls: ["https://www.lvmh.cn/job-offers?keyword=marketing&location=Shanghai"],
  },
  {
    id: "sephora",
    company: "Sephora 丝芙兰",
    industry: "美妆零售",
    priority: "A",
    brands: ["Sephora"],
    careersUrl: "https://www.lvmh.cn/job-offers",
    searchUrls: ["https://www.lvmh.cn/job-offers?keyword=Sephora&location=Shanghai"],
  },
  {
    id: "kering",
    company: "Kering",
    industry: "奢侈品 / 零售",
    priority: "A",
    brands: ["Gucci", "Saint Laurent", "Bottega Veneta", "Balenciaga", "Kering Eyewear"],
    careersUrl: "https://careers.kering.com/careers",
    searchUrls: ["https://careers.kering.com/careers?location=Shanghai&keyword=marketing"],
  },
  {
    id: "richemont",
    company: "Richemont",
    industry: "奢侈品 / 珠宝腕表",
    priority: "B",
    brands: ["Cartier", "Van Cleef & Arpels", "Piaget", "Montblanc", "IWC"],
    careersUrl: "https://www.richemont.com/en/home/talent/view-our-jobs/",
    searchUrls: ["https://www.richemont.com/en/home/talent/view-our-jobs/?location=Shanghai"],
  },
  {
    id: "hermes",
    company: "Hermès",
    industry: "奢侈品 / 零售",
    priority: "B",
    brands: ["Hermès"],
    careersUrl: "https://www.hermes.cn/cn/en/content/220631-join-hermes/",
    searchUrls: ["https://www.hermes.cn/cn/en/content/220631-join-hermes/"],
  },
  {
    id: "chanel",
    company: "Chanel",
    industry: "奢侈品 / 美妆 / 零售",
    priority: "A",
    brands: ["Chanel Fashion", "Chanel Fragrance & Beauty", "Chanel Watches & Fine Jewelry"],
    careersUrl: "https://www.chanel.cn/cn/careers/",
    searchUrls: ["https://www.chanel.cn/cn/careers/"],
  },
  {
    id: "prada",
    company: "Prada Group",
    industry: "奢侈品 / 零售",
    priority: "B",
    brands: ["Prada", "Miu Miu", "Church's", "Car Shoe"],
    careersUrl: "https://www.pradagroup.com/en/talents/job-opportunities.html",
    searchUrls: ["https://www.pradagroup.com/en/talents/job-opportunities.html"],
  },
  {
    id: "burberry",
    company: "Burberry",
    industry: "奢侈品 / 零售",
    priority: "A",
    brands: ["Burberry"],
    careersUrl: "https://burberrycareers.com/content/China/?locale=zh_CN",
    searchUrls: ["https://burberrycareers.com/search-jobs/Shanghai/25173/1814991-1796231-1796236/4"],
  },
  {
    id: "tapestry",
    company: "Tapestry",
    industry: "轻奢 / 零售",
    priority: "B",
    brands: ["Coach", "Kate Spade", "Stuart Weitzman"],
    careersUrl: "https://careers.tapestry.com/",
    searchUrls: ["https://careers.tapestry.com/search/?q=marketing&locationsearch=Shanghai"],
  },
  {
    id: "ralph-lauren",
    company: "Ralph Lauren",
    industry: "时尚 / 零售",
    priority: "B",
    brands: ["Ralph Lauren"],
    careersUrl: "https://careers.ralphlauren.com/",
    searchUrls: ["https://careers.ralphlauren.com/search/?q=marketing&locationsearch=Shanghai"],
  },
  {
    id: "pvh",
    company: "PVH",
    industry: "时尚 / 零售",
    priority: "B",
    brands: ["Tommy Hilfiger", "Calvin Klein"],
    careersUrl: "https://careers.pvh.com/jobs/search",
    searchUrls: ["https://careers.pvh.com/jobs/search?keyword=marketing&location=Shanghai"],
  },
  {
    id: "capri",
    company: "Capri Holdings",
    industry: "奢侈品 / 轻奢 / 零售",
    priority: "B",
    brands: ["Michael Kors", "Jimmy Choo", "Versace"],
    careersUrl: "https://www.capriholdings.com/people/Join-Us/default.aspx",
    searchUrls: ["https://www.capriholdings.com/people/Join-Us/default.aspx"],
  },
  {
    id: "swatch",
    company: "Swatch Group",
    industry: "奢侈品 / 腕表零售",
    priority: "B",
    brands: ["Omega", "Longines", "Tissot", "Swatch", "Breguet"],
    careersUrl: "https://www.swatchgroup.com/en/careers-swatch-group",
    searchUrls: ["https://www.swatchgroup.com/en/careers-swatch-group"],
  },
  {
    id: "pandora",
    company: "Pandora",
    industry: "珠宝 / 零售",
    priority: "B",
    brands: ["Pandora"],
    careersUrl: "https://pandoragroup.com/careers",
    searchUrls: ["https://pandoragroup.com/careers?location=Shanghai"],
  },
  {
    id: "swarovski",
    company: "Swarovski",
    industry: "珠宝 / 零售",
    priority: "B",
    brands: ["Swarovski"],
    careersUrl: "https://jobs.swarovski.com/",
    searchUrls: ["https://jobs.swarovski.com/search/?q=marketing&locationsearch=Shanghai"],
  },
];

const sourceOrigins = {
  loreal: ["法国", "欧美"],
  elcompanies: ["美国", "欧美"],
  shiseido: ["日本", "日本"],
  henkel: ["德国", "欧美"],
  pg: ["美国", "欧美"],
  unilever: ["英国/荷兰", "欧美"],
  beiersdorf: ["德国", "欧美"],
  kenvue: ["美国", "欧美"],
  haleon: ["英国", "欧美"],
  reckitt: ["英国", "欧美"],
  colgate: ["美国", "欧美"],
  "kimberly-clark": ["美国", "欧美"],
  scjohnson: ["美国", "欧美"],
  kao: ["日本", "日本"],
  coty: ["美国", "欧美"],
  amorepacific: ["韩国", "韩国"],
  loccitane: ["法国", "欧美"],
  clarins: ["法国", "欧美"],
  puig: ["西班牙", "欧美"],
  "mary-kay": ["美国", "欧美"],
  nestle: ["瑞士", "欧美"],
  mars: ["美国", "欧美"],
  mondelez: ["美国", "欧美"],
  danone: ["法国", "欧美"],
  "coca-cola": ["美国", "欧美"],
  pepsico: ["美国", "欧美"],
  ferrero: ["意大利", "欧美"],
  "jde-peets": ["荷兰", "欧美"],
  starbucks: ["美国/中国合资", "欧美"],
  "ab-inbev": ["比利时/巴西", "欧美"],
  diageo: ["英国", "欧美"],
  "pernod-ricard": ["法国", "欧美"],
  heineken: ["荷兰", "欧美"],
  carlsberg: ["丹麦", "欧美"],
  bacardi: ["百慕大", "欧美"],
  "suntory-global-spirits": ["日本", "日本"],
  "remy-cointreau": ["法国", "欧美"],
  "general-mills": ["美国", "欧美"],
  kellanova: ["美国", "欧美"],
  "kraft-heinz": ["美国", "欧美"],
  mccormick: ["美国", "欧美"],
  fonterra: ["新西兰", "大洋洲"],
  frieslandcampina: ["荷兰", "欧美"],
  arla: ["丹麦", "欧美"],
  "barry-callebaut": ["瑞士", "欧美"],
  barilla: ["意大利", "欧美"],
  lindt: ["瑞士", "欧美"],
  ikea: ["瑞典", "欧美"],
  costco: ["美国", "欧美"],
  decathlon: ["法国", "欧美"],
  uniqlo: ["日本", "日本"],
  muji: ["日本", "日本"],
  nike: ["美国", "欧美"],
  adidas: ["德国", "欧美"],
  puma: ["德国", "欧美"],
  skechers: ["美国", "欧美"],
  "new-balance": ["美国", "欧美"],
  asics: ["日本", "日本"],
  on: ["瑞士", "欧美"],
  lululemon: ["加拿大", "欧美"],
  hm: ["瑞典", "欧美"],
  inditex: ["西班牙", "欧美"],
  gap: ["美国", "欧美"],
  levi: ["美国", "欧美"],
  vf: ["美国", "欧美"],
  "under-armour": ["美国", "欧美"],
  columbia: ["美国", "欧美"],
  dyson: ["英国/新加坡", "欧美"],
  philips: ["荷兰", "欧美"],
  lego: ["丹麦", "欧美"],
  mattel: ["美国", "欧美"],
  hasbro: ["美国", "欧美"],
  lvmh: ["法国", "欧美"],
  sephora: ["法国", "欧美"],
  kering: ["法国", "欧美"],
  richemont: ["瑞士", "欧美"],
  hermes: ["法国", "欧美"],
  chanel: ["法国", "欧美"],
  prada: ["意大利", "欧美"],
  burberry: ["英国", "欧美"],
  tapestry: ["美国", "欧美"],
  "ralph-lauren": ["美国", "欧美"],
  pvh: ["美国", "欧美"],
  capri: ["美国", "欧美"],
  swatch: ["瑞士", "欧美"],
  pandora: ["丹麦", "欧美"],
  swarovski: ["奥地利", "欧美"],
};

careerSources.forEach((source) => {
  const [originCountry = "未标注", originRegion = "其他"] = sourceOrigins[source.id] || [];
  source.originCountry = originCountry;
  source.originRegion = originRegion;
});

module.exports = {
  careerSources,
  negativeTitleKeywords,
  profileKeywords,
  targetKeywordGroups,
};
